import ctypes
ctypes.windll.kernel32.SetConsoleTitleW("The Quiz Game")
print("")
print("")
print("     ##############################################################################################################    ")
print("     ##############################################################################################################    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                The Quiz                                                ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("")
print("                                                  PRESS ENTER TO START                                                ")
print("")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ##############################################################################################################    ")
print("     ##############################################################################################################    ")
Q0 = input("")
score = 0
questions = 0
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("     Score: " + str(score) + "")
print("")
print("     ##############################################################################################################    ")
print("     ##############################################################################################################    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                          What Color Is The Sky?                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                               Your Answer                                              ###    ")
print("     ###                                                                                                        ###    ")
print("     ##############################################################################################################    ")
print("     ##############################################################################################################    ")
print("")
print("")
print("")

Q1 = input("                                                     $ ")
if Q1 == "blue":
        score += 5
        questions += 1

print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("     Score: " + str(score) + "")
print("")
print("     ##############################################################################################################    ")
print("     ##############################################################################################################    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                           What Does HDMI Mean?                                         ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                               Your Answer                                              ###    ")
print("     ###                                                                                                        ###    ")
print("     ##############################################################################################################    ")
print("     ##############################################################################################################    ")
print("")
print("")
print("")

Q2 = input("                                                     $ ")

if Q2 == "high definition multimedia interface":
        score += 5
        questions += 1
    
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("     Score: " + str(score) + "")
print("")
print("     ##############################################################################################################    ")
print("     ##############################################################################################################    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                     What Coding Launguage Is This?                                     ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                               Your Answer                                              ###    ")
print("     ###                                                                                                        ###    ")
print("     ##############################################################################################################    ")
print("     ##############################################################################################################    ")
print("")
print("")
print("")

Q3 = input("                                                     $ ")

if Q3 == "python":
        score += 5
        questions += 1

print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("     ##############################################################################################################    ")
print("     ##############################################################################################################    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                              ANSWER SHEET                                              ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###           Q1. blue                                                                                     ###    ")
print("     ###                                                                                                        ###    ")
print("     ###           Q2. high definition multimedia interface                                                     ###    ")
print("     ###                                                                                                        ###    ")
print("     ###           Q3. python                                                                                   ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                   TOTAL                                                ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("")
print("                                               TOTAL SCORE: " + str(score) + " / 15")
print("")
print("                                QUESTIONS ANSWERED CORRECT: " + str(questions) + " / 3")
print("")
print("     ###                                                                                                        ###    ")
print("     ###                                                                                                        ###    ")
print("     ###      Press The ENTER Key To Exit                         Scroll Up To Review All Questions Answered    ###    ")
print("     ###                                                                                                        ###    ")
print("     ##############################################################################################################    ")
print("     ##############################################################################################################    ")
Q3 = input("")

